# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Download Vim source
        run: |
          curl -O -L -s https://github.com/vim/vim/archive/v8.2.2445.zip
          powershell Expand-Archive -Path .\v8.2.2445.zip -DestinationPath .
          
      - name: Compile Vim
        shell: cmd
        run: |
          cd vim-8.2.2445
          "%VCVARSALL%" amd64_arm64
          nmake -f Make_mvc.mak GUI=yes IME=yes MBYTE=yes ICONV=yes DEBUG=no
